# Generated by Django 4.2 on 2023-04-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_image_alter_category_id_alter_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_iamge',
            field=models.ImageField(default='C:/Users/dmaso/OneDrive/Desktop/R_School_Leaders/resilient_school_leaders/static/media/card-1.jpg', upload_to='media/'),
        ),
    ]
