# Generated by Django 4.2 on 2023-05-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_rename_category_iamge_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
