# Generated by Django 4.2 on 2023-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
