# Generated by Django 4.2.1 on 2023-07-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emailsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
